### ISSUE TITLE
Should Github Actions CI builds use -j2?

### ISSUE THREAD

**Issue by jdchristensen** [HoTT/HoTT#1266]
The VMs have two cores.  But do all of the jobs share one VM, or do they get independent VMs?

**Comment by Alizter** [comment]
I think it would be worth a try. @JasonGross what do you think?

**Comment by abooij** [comment]
The CI script [already](https://github.com/HoTT/HoTT/blob/614641b0fc56b01256c338b57f722b6290e73220/.github/workflows/ci.yml#L85) partially use `-j2`:
```yml
    - name: Build with timing
      run: |
        etc/coq-scripts/timing/make-pretty-timed.sh -j2
```
`make-pretty-timed.sh` is the part of the CI that takes the longest. Using `-j2` on the other `make`s does not result in a noticeable improvement: compare [without](https://github.com/abooij/HoTT/runs/464576615?check_suite_focus=true) and [with](https://github.com/abooij/HoTT/runs/464581263?check_suite_focus=true).
